// <auto-generated />
using DistSysAcw.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DistSysAcw.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20210321123731_Migration2")]
    partial class Migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DistSysAcw.Models.ArchivedLog", b =>
                {
                    b.Property<string>("LogID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogID");

                    b.ToTable("ArchivedLogs");
                });

            modelBuilder.Entity("DistSysAcw.Models.Log", b =>
                {
                    b.Property<string>("LogID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LogDateTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserApiKey")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LogID");

                    b.HasIndex("UserApiKey");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DistSysAcw.Models.User", b =>
                {
                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApiKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DistSysAcw.Models.Log", b =>
                {
                    b.HasOne("DistSysAcw.Models.User", null)
                        .WithMany("Logs")
                        .HasForeignKey("UserApiKey");
                });

            modelBuilder.Entity("DistSysAcw.Models.User", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
